//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotifyPlaylistAntiTakedown.Properties {
    
   
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string accountToken {
            get {
                return ((string)(this["accountToken"]));
            }
            set {
                this["accountToken"] = value;
            }
        }
    }
}
